* Tarea hecha en casa
안녕하세요!

** 단어
빨리 \[\rightarrow\] rapido
버스 정류장 parada de colectivo
케잌 \[\rightarrow\] torta
그래서 \[\rightarrow\] por eso
한글학교 \[\rightarrow\] escuela de coreano
생일 파티 \[\rightarrow\] fiesta de cumpleaños
축구 \[\rightarrow\] fútbol
도서관 \[\rightarrow\] biblioteca
수영장 \[\rightarrow\] pileta

* 복습
Voy a armar 3 oraciones en voz alta y despues escribirlas aca

어제 저는 백화점에서 모자를 샀어요

다음 주 일요일에 한국어 수업을 있 =을= 거예요

El verbo 있다 va siempre con =이=

이따가 이모 하고 어마 하고 한국음식을 목을 거예요

=Nota=: Aca se que voy a comer, si estoy con mi familia ya en mi casa y se que voy a comer con ellos, tengo que usar futuro o presente? Por que me acuerdo que hay veces que si sabes que vas a ver a la persona, lo decis en presente y si cabe la posibilidad de que no los veas, se escribe en futuro, no estoy muy seguro de esto

Se usa futuro cuando existe la probabilidad de que suceda o que no suceda.
Si es algo que si o si va a pasar, se dice en presente

누가 = quien?
어디에서 = donde?
무슨 = que tipo? => Se responde con el nombre de la pelicula



* 주간 요약

*운영체제*: Operating Systems

이번 주 월요일 하고 화요일 하고 수요일에 제가 집에서 데이터베이스를 공부했어요. 그리고 화요일에 운영체제 시험도 있었어요. 어제 밤에 집에서 친구하고 영화를 봤어요.


=Pregunta=: 쉬려고 es descansar fisicamente

무슨 영화를

영화를 좋아해요?
  네, 좋아해요, 그런데 다 안 봤어요. 너부 길었어요 그리고 시간이 없었어요.

* Voy al baño y vengo

화장실에 갔다 올게요.

사무실에 갔다 올게요


* How to answer

** 잘 지냈어? - Tuteando

너, 잘 지냈어. 너는? (너 = tu en trato informal)
너, 잘 지냈어요, 후안 씨는요?
=Aca no es exactamente "y vos juan?", pero es una expresion que significa eso=


아니요, 너무 바빴어요 (ocupado)

아니요, 좀 아팠어요 (enfermo)

응, 그냥 그래요 ("bien qcy (mas negativo que positivo)") 그럭저럭

*
